### ISSUE TITLE
Opening a bigger org file is very slow

### ISSUE THREAD

**Issue by jceb** [jceb/vim-orgmode#103]
A moderately big file of 400 lines takes a noticable time to open in vim. Larger files like the orgguide take several seconds to open. For sure this is far too slow. It actually has something to do with the following setting:

setlocal foldexpr=GetOrgFolding()

**Comment by maxigaz** [comment]
Hi @jceb! FIrst of all, thank you for your work!

I have a .org file converted from .md with Pandoc that is over 800 lines long. When I open it with Neovim 0.1.7, and not just opening it but also switching between insert and normal modes and making changes (such as the insertion of headings) are also quite slow: I have 1-2 second long lags each time while I don’t have this problem in the case of files with other formats.

**Comment by jceb** [comment]
Yes, that's a problem that I also noticed.  Maybe you can open a new issue since this one is closed.
