### ISSUE TITLE
Error messages for latin-1 files

### ISSUE THREAD

**Issue by svenha** [jceb/vim-orgmode#118]
I receive a traceback when editing a .org fiile with latin-1 characters not contained in ascii.
The traceback ends with the following line:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 4: invalid continuation byte

Can I tell vim-orgmode to switch from utf-8 to latin-1?

**Comment by svenha** [comment]
I don't know how this was fixed. But in the current git version (using python3), the problem disappeared. Great!

**Comment by Ron89** [comment]
hmm, we have paid much attentions to strings' encodings while writing python3 supported version. Perhaps unintentionally we solved the issue. Quite a nice surprise~ 😄
