### ISSUE TITLE
Error "Speeddating plugin not installed. Please install it."

### ISSUE THREAD

**Issue by shalomb** [jceb/vim-orgmode#120]
When opening an .org file in vim (not gvim), the following message is encountered

```
Speeddating plugin not installed. Please install it. 
Press ENTER or type command to continue
```

but issuing  :SpeedDatingFormat in vim lists all the formats as expected.

**Comment by kevinlawler** [comment]
Installing speeddating from here solved this problem for me: http://www.vim.org/scripts/script.php?script_id=2120

**Comment by z0xyz** [comment]
@kevinlawler thanks for pinpointing that it's an actual dependency plugin
