### ISSUE TITLE
Suggested plugins: pathogen should be first

### ISSUE THREAD

**Issue by OliKn** [jceb/vim-orgmode#135]
pathogen should not be near the end of the list, it would be better placed at the beginning.
May be inside 'Installation', before installing the vimball and it should be mentioned that it is a bit different when using pathogen:

Insted of
    :so %
use this
    :UseVimball [path]

**Comment by XVilka** [comment]
Fixed in https://github.com/jceb/vim-orgmode/commit/c6cd668ed13af85d8292b524f827e729bf70ea0f
