### ISSUE TITLE
Improve inline syntax highlight

### ISSUE THREAD

**Issue by astery** [jceb/vim-orgmode#147]
Is it possible to insert code snippets with syntax highlight?

**Comment by jceb** [comment]
@riazrizvi I haven't tried the feature yet.  However, it seems like you need to install the https://github.com/vim-scripts/SyntaxRange plugin.  I found the clue in this commit https://github.com/jceb/vim-orgmode/commit/9e8f5e50f28f98dbea97916805bc715b90eb6b56.  Hope it helps.

**Comment by execb5** [comment]
Did anyone manage to this in a better way than having to manually change the [syntax/org.vim](https://github.com/jceb/vim-orgmode/blob/master/syntax/org.vim) file to add languages?

**Comment by jceb** [comment]
Well, we could make it configurable, i.e. let the user define a list of supported languages .. or even better, extract the language dynamically.

**Comment by execb5** [comment]
Dynamically would be the best, but if it could start with something in vimrc would be great already.

**Comment by XVilka** [comment]
You can use Markdown syntax highlight as an example of the possible settings:
- https://github.com/plasticboy/vim-markdown#fenced-code-block-languages
