### ISSUE TITLE
Agenda view: list index out of range?

### ISSUE THREAD

**Issue by jpotier** [jceb/vim-orgmode#166]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/eeva/.vim/bundle/vim-orgmode/ftplugin/orgmode/plugins/Agenda.py", line 152, in list_next_week
        last_date = raw_agenda[0].active_date
    IndexError: list index out of range

Is it comming from my org file? It was running fine with emacs org mode though.
This happens with plugin pulled from git today.

**Comment by Lucas1993** [comment]
Hi,

I have the same error. 
In Agenda.py, the line that crashes is line number 171:
```#bufname = os.path.basename(vim.buffers[h.document.bufnr].name) ```
I tried changing ```vim.buffers[h.document.bufnr].name``` to a hardcoded name, and it worked.

Don't know why is it breaking, though. Didn't look at it too much.
