### ISSUE TITLE
Issue with TODO items and automatic updating of [%]  and [/] in header.

### ISSUE THREAD

**Issue by theboocock** [jceb/vim-orgmode#172]
HI All,

I am having trouble reproducing the percentages and number of finished tasks as shows here in the example file, My file looks like.

>
    organize part [%]
    ** TODO call peoplee [/]
    *** TODO PETER
    *** DONE SARAH
    ** TODO BY food
    ** DONE TALK to nei
<

If I run <localleader>c# both the [%] and [/] are not updated to the expected values.

Does anyone have any advice.

The relevant section of the org guide file follows. 

Breaking tasks down into subtasks~

It is often advisable to break down large tasks into smaller, manageable
subtasks. You can do this by creating an outline tree below a TODO item,
with detailed subtasks on the tree. To keep the overview over the
fraction of subtasks that are already completed, insert either ‘[/]’ or
‘[%]’ anywhere in the headline. These cookies will be updated each time
the TODO status of a child changes, or when pressing C-c C-c on the
cookie. For example:

>
    * Organize Party [33%]
    ** TODO Call people [1/2]
    *** TODO Peter
    *** DONE Sarah
    ** TODO Buy food
    ** DONE Talk to neighbor
<
                        
<localleader>c#	        Update the checkboxes status of current heading. It also
                        update the heading status too.

**Comment by Ron89** [comment]
It appears that this issue is already solved. Appending [%] or [/] after the heading or checkbox/plainlist with checkbox children will do. The function is also documented in orgguide.txt. Closing the issue.

**Comment by BigPeet** [comment]
How is this issue closed? It still doesn't work as it is currently documented. It only checks direct children with a check boxes, but it completely ignores TODO or DONE. This example taken from the documentation does NOT work:

`* Organize Party [33%]
** TODO Call people [1/2]
*** TODO Peter
*** DONE Sarah
** TODO Buy food
** DONE Talk to neighbor`

It won't update the % of "Organize Party" and it won't update the / of Call People unless you replace every TODO and DONE with check boxes.
