### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by mcepl** [jceb/vim-orgmode#180]
I have installed vim-orgmode to my Pathogen bundle and opened a new `~/todo.org` file. I got on start this error:
```
Error detected while processing /home/matej/archiv/knihovna/repos/vim-bundle/vim-o
rgmode/syntax/org.vim:
line  202:
E117: Unknown function: <SNR>92_ReadTodoKeywords
```
What's wrong with me? Do I miss some dependency?

**Comment by jceb** [comment]
Would you make sure that you have the following line in your vimrc?

`filetype plugin indent on`

**Comment by mcepl** [comment]
```
matej@mitmanek: ~$ grep 'filetype plugin indent on' ~/.vimrc
  filetype plugin indent on
matej@mitmanek: ~$
```

**Comment by jceb** [comment]
Whoops, you've probably set `let g:loaded_org_syntax = 1` somewhere in your vimrc.  This leads to the issue of a call of a non-existing function.

**Comment by mcepl** [comment]
Right, there was another copy of `vim-orgmode` in ~/.vim itself.
