### ISSUE TITLE
toggle_folding error

### ISSUE THREAD

**Issue by gerroon** [jceb/vim-orgmode#189]
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kursad/.vim/bundle/vim-orgmode/ftplugin/orgmode/_vim.py", line 82, in r
    res = f(*args, **kwargs)
  File "/home/xxxxx/.vim/bundle/vim-orgmode/ftplugin/orgmode/plugins/ShowHide.py", line 101, in toggle_folding
    vim.command((u'%d,%dfoldclose!' % (heading.start_vim, heading.end_of_last_child_vim)).encode(u'utf-8'))
vim.error: Vim(foldclose):E490: No fold found

**Comment by jceb** [comment]
Hi, please add more details about the issue.  What did you do too reproduce the error.

I think I've seen this error before.  Did you install the plugin properly?  have a look at the installation section.

**Comment by gerroon** [comment]
Hi

I installed the plugin using addon manager. This error happens when I try to do plain folding with tab. 

I am on Debian Jessie 64

thanks

**Comment by jceb** [comment]
It might be that the addon manager isn't working properly.  Please read the installation section in this file: https://github.com/jceb/vim-orgmode/blob/master/doc/orgguide.txt

**Comment by modk** [comment]
Getting the same error when the file contains hyphens e.g.
works with servertodo.org and not with server-todo.org

**Comment by Ron89** [comment]
@modk I have tried files with hyphen in its name and couldn't reproduce the error. Could you share a minimum structure of your .org file and your fold method setting for Vim?

**Comment by modk** [comment]
Strange it only happens with exactly this one file in a specific directory. No idea what's causing this but it's most likely a problem not directly related to vim-orgmode. Sorry for the noise.
