### ISSUE TITLE
Implement keyboard commands for plain lists

### ISSUE THREAD

**Issue by mrbiber** [jceb/vim-orgmode#190]
It would be great to have the keyboard commands for plain lists implemented ([see](http://orgmode.org/manual/Plain-lists.html#Plain-lists)), in particular the ones for adding items and cycling through them.

**Comment by Ron89** [comment]
I have created a set of new key binding: 

    * `<LocalLeader>cl` to create new plainlist item below;
    * `<LocalLeader>cL` to create new plainlist item above.

Accordingly, keybinding `<LocalLeader>c[n/N]` are now fully restricted to
creating checkbox undonditionally.

Sorry for the late fix. Hope you find new keybindings satisfying.
