### ISSUE TITLE
vim.org calendar.vim doesn't work with vim-orgmode

### ISSUE THREAD

**Issue by adam-m-jcbs** [jceb/vim-orgmode#197]
First off, I love vim-orgmode!  I went to the dark side and used EMACS just to use orgmode.  I much prefer to stick with vim!

I noticed that vim-orgmode's calendar feature doesn't work with calendar.vim (http://www.vim.org/scripts/script.php?script_id=52).  This is because it doesn't appear to implement the :CalendarH command.  Instead, you need to use this one from GitHub: https://github.com/mattn/calendar-vim, which, oddly, cites calendar.vim at the top even though it's not a mirror of it.

Not sure how you'd like to proceed, but in my fork of vim-orgmode I changed the orgguide.txt to direct you to the appropriate calendar plugin.  If it works with your vision for vim-orgmode, feel free to accept it as a pull request!

**Comment by adam-m-jcbs** [comment]
For convenience, here's the pull request: https://github.com/jceb/vim-orgmode/pull/198

**Comment by Ron89** [comment]
He cited it because it was his plugin all along. And in case you didn't notice, the last update on vim.org repo was early 2013...

**Comment by jceb** [comment]
@adam-m-jcbs thank you for pointing out the issue and sending a pull request and please excuse the late response.
