### ISSUE TITLE
Refresh vim.org scripts page 

### ISSUE THREAD

**Issue by SteveSimmons** [jceb/vim-orgmode#200]
Jan, could you please upload a new release on vim.org (http://www.vim.org/scripts/script.php?script_id=3642) and edit the description there to point to your GH repo? 
That would help reassure Vim users that vim-orgmode is still viable.

**Comment by jceb** [comment]
Hi Steve, thanks for the suggestion.  I uploaded a new release.  The GH repo was already on the page.
