### ISSUE TITLE
localleader bindings not working

### ISSUE THREAD

**Issue by rstacruz** [jceb/vim-orgmode#205]
I can't seem to trigger any localleader key bindings such as `<localleader>sa`. I have done `let g:maplocalleader=","` and `let g:mapleader=","`.

Sorry I haven't had the chance to create a reduced use case, but FWIW, I'm using NVIM 0.1.0 (with Python working) and Vim 7.4 via MacVim (python also working). My vimfiles are [here](https://github.com/rstacruz/vimfiles) and they're managed using vim-plug.

**Comment by jceb** [comment]
I have the following in my vimrc and it works fine:
`let maplocalleader = ','`

**Comment by brunobeltran** [comment]
Had the same issue, turns out using `let maplocalleader` instead of `let g:maplocalloader` fixed it for me.
