### ISSUE TITLE
vim-orgmode load error

### ISSUE THREAD

**Issue by NickBusey** [jceb/vim-orgmode#207]
Just installed the plugin, got the following error trying to load a .org file:

Error detected while processing /Users/nick/.vim/bundle/vim-orgmode/ftplugin/org.vim:
line   93:
Traceback (most recent call last):
  File "<string>", line 10, in <module>
ImportError: No module named orgmode._vim
Error detected while processing function <SNR>22_OrgRegisterMenu:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'ORGMODE' is not defined

**Comment by jceb** [comment]
This is a python error message.  Somehow it can't find the orgmode module.  Please go through the installation steps again.  I assume that some crucial part is missing in your configuration.

Maybe there's someone else around who has experience with MacOS X and can help with the installation.  Anyone around?

**Comment by jceb** [comment]
Hm, no response - I'll close it for the moment.

**Comment by cmatzenbach** [comment]
Was there ever a solution for this issue?  I just tried to install this plug-in and am getting the same steps on startup.

Info:
OS: MacOS Sierra 10.12.2
Vim: Neovim 2.0dev
Term: iTerm2 with ohmyzsh

Install steps - went through orgguide.txt, first installing all suggested plugins with vim-plug.  Then restarted neovim, added vim orgmode and tried to install with vim-plug.  It did install, but on startup I get this error message:

"test.org" 0L, 0C
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/Users/matzy/.config/nvim/plugged/vim-orgmode/ftplugin/orgmode/_vim.py", line 22, in <module>

    from orgmode.vimbuffer import VimBuffer
  File "/Users/matzy/.config/nvim/plugged/vim-orgmode/ftplugin/orgmode/vimbuffer.py", line 30, in <mo
dule>
    from orgmode.liborgmode.documents import Document, MultiPurposeList, Direction
  File "/Users/matzy/.config/nvim/plugged/vim-orgmode/ftplugin/orgmode/liborgmode/documents.py", line
 16, in <module>
    from orgmode.liborgmode.headings import Heading, HeadingList
  File "/Users/matzy/.config/nvim/plugged/vim-orgmode/ftplugin/orgmode/liborgmode/headings.py", line
16, in <module>
    from orgmode.liborgmode.checkboxes import Checkbox, CheckboxList
  File "/Users/matzy/.config/nvim/plugged/vim-orgmode/ftplugin/orgmode/liborgmode/checkboxes.py", lin
e 20, in <module>
    from orgmode.liborgmode.dom_obj import DomObj, DomObjList, REGEX_SUBTASK, REGEX_SUBTASK_PERCENT,
REGEX_HEADING, RE
Error detected while processing function <SNR>130_OrgRegisterMenu[1]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'ORGMODE' is not defined

I have both python2 (latest) and python3 installed.  Are there any python plugins I need to install myself from pip or pip3?

**Comment by jceb** [comment]
No, there has been no solution to this issue.  I guess it has something to do with neovim's python configuration.  vim-orgmode should work with both, python2 and python3.  Since I'm not a mac user I can't reproduce the issue.  I'd be happy if you could dig deeper into it.

**Comment by hrafeiro** [comment]
I'm right now in a MacOsX machine. I installed vim-orgmode using Vundle and it partially works. When I open a .org file it doesn't recognize as org and typing
`:set filetype=org` 
I enter in org mode. I can work partially with vim-orgmode, although some things are still not working properly, for example after
`<localleader>cat`
I receive the following error
<img width="1411" alt="screenshot 2017-02-18 19 19 36" src="https://cloud.githubusercontent.com/assets/2779138/23097927/37941be4-f60f-11e6-9dd7-1f8613cc7466.png">
Any suggestion on how to repair this error?

**Comment by sotte** [comment]
Just letting you know vim-orgmode works with neovim for me (on Ubuntu).

@ cmatzenbach
For neovim you have to install the neovim python adapter: `pip install --user neovim`.

@hrafeiro 
I think you have a different problem related to the org_agenda_files. See the other issue.

**Comment by ptmminh** [comment]
I ran into the same problem. The issue is that I didn't properly uninstall previously, make sure you remove `orgmode` from `~/.vim/ftdetect` and `~/.vim/ftplugin` if you're using one of the package managers.
