### ISSUE TITLE
Unable to toggle checkbox when embeded with plainlist

### ISSUE THREAD

**Issue by Ron89** [jceb/vim-orgmode#209]
In the example down below:

      - [ ] Task A regarding to information:
            - Info 1
            - Info 2
            - Info 3
      - [ ] Task B
      - [ ] Task C
            - [ ] Task C-1
            - [ ] Task C-2

The check box on Task A is impossible to toggle with `<LocalLeader>cc`. Is this
a designed choice or is it really an issue like I suspected? I tried toggling
the exact case in Emacs's orgmode, and the toggling works fine.

**Comment by jceb** [comment]
I guess this is an issue.  Since there are subitems the code assumes that these are not done although they can't be checked.

**Comment by Ron89** [comment]
I'm not familiar with your structure, but is it simple to take `(list-identifier) (check-box-identifier)` rather than '(list-identifier)' as an subitem indicator?

**Comment by jceb** [comment]
I haven't written the checkbox functionality and can't say much about how it works.  Would you be able to check the code and verify your assumption?

**Comment by Ron89** [comment]
Ya, I'll look into it. When I'm done, I'll send a PR.

**Comment by jceb** [comment]
Merged.
