### ISSUE TITLE
Heading Tree structure broken when non-heading content inserted in between

### ISSUE THREAD

**Issue by Ron89** [jceb/vim-orgmode#216]
As a simple example, in following structure
```
    * Heading-1-1
    content
    ** Heading-2-1
    ** Heading-2-2
    * Heading-1-2
```
When using `<localleader>hh` on `Heading-1-1`, insead of inserting a heading
before `Heading-1-2`, the new heading will be place immediately after content.
This design prevents user from adding comment on the heading before moving into
deeper headings. It also differs from how orgmode on emacs behaves(which is how
it should have been). I believe the cause of the issue is that subtree parsing
stops at the first non-heading content. Hence the followed subtree were
mistreated as siblings rather than children.

**Comment by Ron89** [comment]
Sorry, I remembered the command wrongly... But still, shouldn't we put the function of `<localleader>h[N/n/h]` in to the document?

**Comment by Ron89** [comment]
Actually, behavior of `<localleader>hh` is still off, since it should have
create a heading before `content` rather than after it. I'll leave this issue
open until

* document on keybinding is finished
* behavior of `<localleader>hh` is corrected

**Comment by jceb** [comment]
Hm, actually I think the behavior is okay.  Creating a heading before `content` is something I wouldn't want to do.  Heading and content belong together in my opinion .. but maybe Emacs org-mode implements things differently.

**Comment by Ron89** [comment]
Technically, " insert heading, taking over all children " should include content. And yes, emacs version handle it differently. But it's your call.

**Comment by Ron89** [comment]
orgguide updated.
