### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by akstrfn** [jceb/vim-orgmode#226]
Hi,

Ubuntu 16.04 now has Vim compiled with python3 as default. This triggers if !has('python') in org.vim. I've checked the python code with python 2to3 converter and it seems that there is not much preventing it from running with python3 support.

Alex

**Comment by Ron89** [comment]
Is there any specific problem after using 16.04? Arch/Manjaro has been defaulting Python3 for years, and I don't have any problem on it.

**Comment by akstrfn** [comment]
I would assume then that you are using vim that is compiled with python2 because there is code that would not work in python3 currently in vim-orgmode.

**Comment by Sean1708** [comment]
@Ron89; in Arch the `python` executable points to Python 3 but in Ubuntu there will be no `python` executable, only a `python3` one. If it works on Arch then it sounds like it's just a case of looking for a `python` or a `python3`.

**Comment by Ron89** [comment]
@Sean1708. No, in Arch, vim is built with both +python and +python3. While in Ubuntu, the maintainer deliberately built vim separately for +python support or +python3 support, and defaulted the +python3 built when installing.

We are thinking about what should we do about this.

**Comment by lobida** [comment]
Hello,
same problem: 
ubuntu16.04: vim --version +cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
so, only support python3, not python2
Jay

**Comment by Ron89** [comment]
Thanks to @akstrfn 's hard work, Python3 support is now added. Please update your vim-orgmode and see if it works for you.

**Comment by keenanratushniak** [comment]
I still can't get this working on ubuntu with vim that only has python3 support and not python support. It looks like all the files should pick up either version of python but I get this:

Error detected while processing /home/****/.vim/ftplugin/org.vim:
line   10:
Unable to start orgmode. Orgmode depends on Vim >= 7.3 with Python support complied in.

Do you have to do anything special for it to pick up python 3?

vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 08 2016 11:38:28)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax

**Comment by akstrfn** [comment]
Can you report the outputs of the: 
```
:echo has('python3')
:echo has('python')
:echo v:version
```

**Comment by keenanratushniak** [comment]
I can't seem to get those echo's to work. I am not using a straight Ubuntu but linux mint 18, so that could be causing some problems for it. Is there something else I could try for you?

**Comment by MrRothstein** [comment]
I'm seeing the same issue with xubuntu:

Error detected while processing /home/<me>/.vim/bundle/vim-orgmode/ftplugin/org.vim:
line   10:
Unable to start orgmode. Orgmode depends on Vim >= 7.3 with Python support complied in.

Plugin is installed with vundle.

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056

:echo has('python3') = 1
:echo has('python') = 0
:echo v:version = 704

**Comment by shabbychef** [comment]
I have the same issue on Ubuntu 16.04.
```
:echo has('python3')
1
:echo has('python')
0
:echo v:version
704
```
yet unable to start orgmode.

**Comment by shabbychef** [comment]
duh, I just understood MrRothstein's comment: I had the 'vanilla' orgmode plugin. Switching to `jceb/vim-orgmode` fixed the issue.
