### ISSUE TITLE
Inserting date from calendar broken with python3 (on Arch linux at least)

### ISSUE THREAD

**Issue by omrihar** [jceb/vim-orgmode#241]
I'm using vim-orgmode with vim 7.4 (patches 1-1797) on arch linux (which has `python` default to python3). When I try to insert a date from the Calendar I get several errors. The first is easy to fix (in `org.vim:155` there is a `print` statement without parentheses, regardless if `s:py_version` is `python` or `python3`. After adding these parentheses, it still fails because `Date` is undefined. I'm not sure how to fix this (otherwise I would submit a pull-request). 

Thanks for a cool plugin!
Omri

**Comment by akstrfn** [comment]
Hi, thanks for reporting. PR #242 fixes the issue.
