### ISSUE TITLE
E117: Unknown function: <SNR>30_ReadTodoKeywords

### ISSUE THREAD

**Issue by athanassis** [jceb/vim-orgmode#248]
Hi,
I use version 0.4.1.
I see that ReadTodoKeywords function is defined OK in the org.vim, I haven't touched it.
However the Todo Keywords work (cycle through values, folding) ok after the document opens.
Any ideas?

Regards,
Thanassis

**Comment by MHohenberg** [comment]
Just want to drop that I have this phenomeon as well on commit  e76c0f0, but only when opening a .org file directly.

**Comment by athanassis** [comment]
It must have been something with old remainings not removed with the installation or something similar. 
After a clean uninstall:
.../vimfiles > find -name "*org*" | xargs rm -rf
and installation the problem is no more visible.

**Comment by Mantissa-23** [comment]
This is still an issue for me on Neovim/Ubuntu 18.04 with 35e9421. Exact error:

```
Error detected while processing /home/username/.local/share/nvim/plugged/vim-orgmode/syntax/org.vim:
line  227:
E117: Unknown function: <SNR>117_ReadTodoKeywords
```

**Comment by cbosoft** [comment]
I am also still experiencing this issue:

`
"a.org" [New File]
Error detected while processing /home/chris/.vim/bundle/vim-orgmode/syntax/org.vim:
line  227:
E117: Unknown function: <SNR>38_ReadTodoKeywords
Press ENTER or type command to continue
`
Vim version:
`
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb  7 2019 19:47:28)
Included patches: 1-877
`

Using github `vim-orgmode` with latest commit dated Wed Jul 25 10:11:03 2018 +0200. 

How could I go about debugging this? I'm pretty new to vim extensions, so the error is a bit of a mystery to me. The function appears to be defined okay in `vim-orgmode/syntax/org.vim`.
