### ISSUE TITLE
Make % jump between < and >

### ISSUE THREAD

**Issue by schoettl** [jceb/vim-orgmode#250]
`%` usese `'matchpairs'` to jump between e.g. `([{}])` (default).

I would love to have `<>` added to the `'matchpairs'`. I think this is a good default for filetype org:
- It is useful when working with timestamps.
- It is useful with code snippets in many languages.
- I cannot think of a situation where it hurts.

I will provide a pull request adding it: `:setlocal matchpairs+=<:>`

BTW: This seems to be the responsibility of the specific filetype plugin as discussed [here at neovim](https://github.com/neovim/neovim/issues/5099).

**Comment by jceb** [comment]
Merged.
