### ISSUE TITLE
org-mode babel plugin for vim-orgmode.

### ISSUE THREAD

**Issue by zacts** [jceb/vim-orgmode#257]
Does vim-orgmode support the babel org-mode plugin? If not, may I request this feature?

**Comment by jceb** [comment]
Would you provide a link to babel and a brief explanation why it would be useful for vim-orgmode?  Thank you.

**Comment by zacts** [comment]
http://orgmode.org/worg/org-contrib/babel/ <-- here is the link. It would be useful to me personally, because it would allow me to write reproducible research papers. See: https://www.jstatsoft.org/article/view/v046i03

**Comment by jceb** [comment]
Sounds good.  I don't have time to implement it.  Please provide a pull request if you want to have it integrated.
