### ISSUE TITLE
Export to anything not working 

### ISSUE THREAD

**Issue by mack1070101** [jceb/vim-orgmode#258]
When I try to export any .org file to any format (HTML, Markdown, PDF, ect.) I get the following error: 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mackenzie/.vim/bundle/vim-orgmode/ftplugin/orgmode/plugins/Export.py", line 108, in tohtml
    ret = cls._export(u'org-html-export-to-html')
  File "/home/mackenzie/.vim/bundle/vim-orgmode/ftplugin/orgmode/plugins/Export.py", line 80, in _export
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
`

I have given both subprocess.py, and Export.py full read, write and execute permissions, I have emacs installed, and the path to emacs properly set.

I'm on Ubuntu 16.04.

Any advice how to fix this error?

**Comment by jceb** [comment]
Do you have Emacs installed?  It's required in order to perform the export.

**Comment by mack1070101** [comment]
Hi, yes I do have emacs installed, and I also have let g:org_export_emacs="/etc/emacs" in my .vimrc

**Comment by jceb** [comment]
Well, that appears to be the issue.  It should point to the executable of emacs rather than the configuration.  Please have a look at the documentation: https://github.com/jceb/vim-orgmode/blob/master/doc/orgguide.txt

Please reopen the issue if it remains.
