### ISSUE TITLE
<leader> should be <localleader>

### ISSUE THREAD

**Issue by tsvibt** [jceb/vim-orgmode#260]
I think that 
ftplugin/orgmode/plugins/EditStructure.py 
line 367 should be
self.keybindings.append(Keybinding(u'<localleader><CR>',  [....]
not
self.keybindings.append(Keybinding(u'<leader><CR>',  [....]

**Comment by jceb** [comment]
Thanks for reporting.  Would you provide a pull request?

**Comment by jbpoittevin** [comment]
PR#268 has been merged.
Closing the issue.
