### ISSUE TITLE
Neovim with Python 3.6

### ISSUE THREAD

**Issue by ggerico** [jceb/vim-orgmode#263]
Orgmode is working in neovim with python 3.5 but not with 3.6 which is the current python version of brew.
Uninstall the 3.6 via brew.

This [link](https://www.python.org/ftp/python/3.5.0/python-3.5.0-macosx10.6.pkg) will install the 3.5 version on OSX.
```bash
pip3 install neovim
pip3 install --upgrade neovim
```
It should work again. :)

**Comment by XVilka** [comment]
I think it is fixed, tried to reproduce but no luck. Can you confirm it was fixed?

**Comment by XVilka** [comment]
Closing as no response, please open a new one if you still meet this bug.
