### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tesujimath** [jceb/vim-orgmode#278]
258 commits and nearly 2 years since v0.5.0.  Can we have a new release, please?

**Comment by zacts** [comment]
I would also be interested with this.

**Comment by zacts** [comment]
Hm... perhaps if @jceb decides to take a break for a while, someone else could pick up the work. If I can learn a bit more of vim-script I might offer like Q1 of 2018.

**Comment by jceb** [comment]
@zacts sure, go ahead with it.  Would you prepare a pull request?  After reviewing it I'd give you write access to the repo.

**Comment by zacts** [comment]
@jceb I'm looking at my schedule and projects, and I'm unfortunately thinking that I likely will not be able to do this right now. Perhaps someone else may be more qualified than me to do this as well.  Maybe mid to late next year I can go for it if no-one steps up by then.

**Comment by zacts** [comment]
i just want to guarantee that I would have the ability and skills to manage this project well, and I'm looking through the code, and I'm not ready yet. Again, perhaps by mid 2018 I'll be ready. Would anyone else be willing to pick this up?

**Comment by zacts** [comment]
I mean let me see. I may be able to go for this January 2018. I will give a definitive answer by December 1st. In the meantime perhaps someone else will step-up who has already contributed.

**Comment by Psirus** [comment]
I've opened up a PR for this, #282. Let me know if anything needs changing.
