### ISSUE TITLE
Install on neovim

### ISSUE THREAD

**Issue by BenJWard** [jceb/vim-orgmode#285]
I've tried to download the orgmode.vba (version 0.5) from the vim.org website as the readme guide suggested, and did :so % but I got messages saying:

```
Error detected while processing /Users/bward/Desktop/orgmode.vba:
line    2:
E492: Not an editor command: UseVimball
Press ENTER or type command to continue
```

What is the correct installation procedure on neovim?

**Comment by Psirus** [comment]
I think installing from vimball is effectively deprecated. I'd suggest using a package manager, for example [Pathogen](https://github.com/tpope/vim-pathogen) or [vim-plug](https://github.com/junegunn/vim-plug).

**Comment by boydkelly** [comment]
The documentation is kind of weird since it recommends pathogen for installing the optional/recommended plugins, but then only suggests installing itself from vmb or vma or using vim-plug or dein.vim.  I was left wondering if I can't use pathogen to install.

**Comment by XVilka** [comment]
I will deprecate the vimball, and add Pathogen, Vundle and Plug as the most popular nowadays.

**Comment by alinoekialo** [comment]
This is now working on neovim, I use it everyday.

**Comment by alinoeabrassart** [comment]
This is now working on neovim, I use it everyday.

**Comment by XVilka** [comment]
Fixed in https://github.com/jceb/vim-orgmode/commit/2fd96452472436c067271d672072696548ddb699

Feel free to open a new issue if you feel something is not clear still.
