### ISSUE TITLE
[doc] install methods in doc cannot work

### ISSUE THREAD

**Issue by Aperjump** [jceb/vim-orgmode#301]
Hi, 
I followed the procedure in documentation and download vim-orgmode from http://www.vim.org/scripts/script.php?script_id=3642. But this file has been outdated. New vim do not support `has('python')`command.

**Comment by ikselven** [comment]
If you use vim >= 8.0, you can make use of the new package-feature and install it the following way:
```bash
$ mkdir -p ~/.vim/pack/git-plugins/start
$ cd ~/.vim/pack/git-plugins/start
$ git clone https://github.com/jceb/vim-orgmode
```

Then, add to your `~/.vimrc`:
```
packloadall
silent! helptags ALL
```
to load all installed packages and update vim's help.

More generally speaking: If you happen to use any plugin manager like Pathogen, Vundle etc. just look at their documentation on how to install a vim plugin by cloning its repository.

**Comment by XVilka** [comment]
Fixed in https://github.com/jceb/vim-orgmode/commit/c6cd668ed13af85d8292b524f827e729bf70ea0f
