### ISSUE TITLE
Fails to start with brew installed nvim 0.3.1, Plug installed vim-orgmode

### ISSUE THREAD

**Issue by DarrienG** [jceb/vim-orgmode#306]
Compiled is also misspelled. 

![screen shot 2018-08-21 at 11 09 46 am](https://user-images.githubusercontent.com/5041953/44410597-c6611880-a532-11e8-905d-a4bbaa590a61.png)

Works fine with my install of Vim 8.

**Comment by akstrfn** [comment]
try ``:checkhealth`` and check if everything is ok with neovim-python.

**Comment by DarrienG** [comment]
Well that was interesting, the python neovim module isn't installed with brew. Sorry about that!

**Comment by jcguu95** [comment]
I had the same problem and solved it by `pip install --upgrade neovim`. See this thread: https://github.com/neovim/neovim/issues/1524
