### ISSUE TITLE
Is this project still under development or just under maintenance or neither? 

### ISSUE THREAD

**Issue by xarthurx** [jceb/vim-orgmode#320]
As asked in the title.

**Comment by lanker** [comment]
https://github.com/jceb/vim-orgmode/issues/262#issuecomment-268625830

**Comment by wbthomason** [comment]
There are still a number of actively developed forks, though it isn't clear if one or another is the "best" to use from a day-to-day standpoint.

**Comment by jceb** [comment]
From my side it's not under development.

**Comment by XVilka** [comment]
@jceb I can step in to help the maintain bugs and pull requests.

**Comment by jceb** [comment]
@XVilka thank you, please do so 👍

**Comment by XVilka** [comment]
@jceb I will need commit rights then.

**Comment by jceb** [comment]
Sure, you'll get that. Maybe you can start preparing some pull requests that I'll look at and then you'll get access rights.

**Comment by XVilka** [comment]
Ok, got it.

**Comment by XVilka** [comment]
These PRs are very simple and ready to be merged right now:
- [Update installation instructions](https://github.com/jceb/vim-orgmode/pull/295) - updated the URL
- [Fix URL in the guide](https://github.com/jceb/vim-orgmode/pull/288)

**Comment by jceb** [comment]
Sounds good, go ahead.

**Comment by AbsurdMagpieScrutinies** [comment]
@XVilka : if you do do that - start maintenance of and accepting pull request for vim-orgmode - that would be great. 

Please do.

**Comment by XVilka** [comment]
@AbsurdMagpieScrutinies I already started. Will require some time to get familiar with the codebase, but should be fine.

**Comment by XVilka** [comment]
Closing this one as "fixed".
