### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by OrionRandD** [jceb/vim-orgmode#328]
For installing, it says:

Open the vimball archive in vim and source it.
$ vim orgmode.vba
  :so %
Where is this orgmode.vba file?
:)

**Comment by XVilka** [comment]
I don't see this line anywhere, it was fixed. Please update your version from git.

**Comment by OrionRandD** [comment]
@XVilka  thx a lot. I just installed it with Vundle. 
I did not see a line in the guide saying that it is possible to install the plugin with Vundle.
:BundleInstall
Perhaps this can be added as well.

**Comment by kazukazuinaina** [comment]
I think `Vundle` is old plugin manager.

I recommend using vim-plug or dein.vim

### URL

**vim-plug**

> https://github.com/junegunn/vim-plug

**dein.vim**

> https://github.com/Shougo/dein.vim

**Comment by OrionRandD** [comment]
I use it because of spf-13 vim version that I run...
https://github.com/spf13/spf13-vim
