### ISSUE TITLE
Is this repo under maintaining?

### ISSUE THREAD

**Issue by yyn19951228** [jceb/vim-orgmode#345]
Thanks for this awesome Plugin! 
But it seems that there are so many issues and no one still maintains the repo.

**Comment by Exr0n** [comment]
+1 This is amazing, but I wonder if anybody is still maintaining this? Do we know what the long term plans for this project are?

Thanks :)

**Comment by XVilka** [comment]
It is *slowly* maintained. Pull requests are welcome.
Here are the near term plans: https://github.com/jceb/vim-orgmode/milestones
