### ISSUE TITLE
Export with images

### ISSUE THREAD

**Issue by jcguu95** [jceb/vim-orgmode#346]
Is it currently possible to render images while exporting? Putting `[[file:./4.jpg][4]]` leads to a hyperlink in the exported HTML and PDF, but does not embed the image within.

**Comment by konradzdeb** [comment]
A discussion on whether this is consistent with the project goal would be helpful. Likely the desire to support exporting with images will open a bunch issues on handling image files (positioning, scaling, etc.). If the one desires to produce visually appealing task list then making use of LaTeX (or any other solution providing desired functionalities) is likely the way to go…

**Comment by jcguu95** [comment]
Gotcha, thanks for sharing. I'm convinced that to use org practically emacs is the way to go. After all there are >100k locs there already. So I will close this request with this comment. Thanks for the hard work!
