### ISSUE TITLE
Universal Text Linking (utl.vim)

### ISSUE THREAD

**Issue by suliveevil** [jceb/vim-orgmode#353]
I forked [Universal Text Linking](http://www.vim.org/scripts/script.php?script_id=293)

https://github.com/suliveevil/utl.vim

If you prefer Git , this will help.

**Comment by mcepl** [comment]
I just wanted to ask … is UTL really necessary. I have just set ``g:netrw_browsex_viewer`` to my preferred URL handler (actually, in my case, it is the Lua script which preprocesses URL and then runs ``xdg-open`` on the result), and it seems to work quite well.

Wouldn’t it be possible to at least make ``netrw`` (which is by default bundled with all vim/neovims) optional handler and not make UTL hard dependency of orgmode?

**Comment by suliveevil** [comment]
utl is made to jump between files, like URL is to jump between webpages.
