### ISSUE TITLE
Example gif font name

### ISSUE THREAD

**Issue by toniz4** [jceb/vim-orgmode#359]
Sorry if this is too unrelated, but i found the font in the readme gif (mylife.gif) very nice and i want to know the name of it

**Comment by Alby407** [comment]
Same here! Would be nice to know the font name.

**Comment by toniz4** [comment]
> Same here! Would be nice to know the font name.

Looking at it again, it looks like [dina](https://www.dcmembers.com/jibsen/download/61/).
