### ISSUE TITLE
Willing to be maintainer

### ISSUE THREAD

**Issue by hawkinsw** [jceb/vim-orgmode#369]
Hello everyone!!

First, thanks for the great work on this plugin.

I just wanted to let you know that I am willing to join the project as a maintainer. I am a user of the plugin but not an expert by any means. If you think that I could help, please let me know!

Thanks again for the plugin and I hope that I can help!
Will

**Comment by hawkinsw** [comment]
Okay. I will start working through some of the issues and do what I can.

**Comment by petRUShka** [comment]
@hawkinsw, there is a performance issue #264. Please take a look at it. It makes combo neovim + vim-orgmode almost useless. And in case of big `.org` files makes even vim very slow.

**Comment by konradzdeb** [comment]
I vote for this to be closed as @jbpoittevin was added as maintainer, RE: #373:
> Thanks a lot! @jbpoittevin I added you as a maintainer. Feel free to extend the LICENSE file etc.

**Comment by jbpoittevin** [comment]
Taking maintainer role, closing issue.
