### ISSUE TITLE
Links no longer visible

### ISSUE THREAD

**Issue by yamsu** [jceb/vim-orgmode#371]
After the recent merge it seems that links are no longer visible

The following is not visible in normal mode, but appears as usual in insert mode
```
[[link]] Text   => Text
[[link][Description]] Text => Text
```

**Comment by yamsu** [comment]
Quick work around is to disable conceal in 
```
pluginfolder/vim-orgmode/ftplugin/org.vim
```
Comment out the following line (line 30)
```
setlocal conceallevel=2 concealcursor=nc
```

**Comment by seflue** [comment]
After doing some debugging, I actually found the source of the problem: If someone is using a plugin, which already shortens links in orgmode-style (like [org.vim](https://github.com/axvr/org.vim) or [vim-polyglot](https://github.com/sheerun/vim-polyglot), the links vanish.
My solution:
In `<plugin_folder>/vim-orgmode/syntax/org.vim` introduce a new global variable at the beginning:
```vim
if !exists("g:conceal_org_hyperlinks")
    let g:vim_orgmode_conceal_hyperlinks=1
endif
```
And then around line 276 wrap the whole highlighting code in an if clause:
```vim
" Hyperlinks: {{{1
if (g:vim_orgmode_conceal_hyperlinks == 1)
  syntax match hyperlink	"\[\{2}[^][]*\(\]\[[^][]*\)\?\]\{2}" contains=hyperlinkBracketsLeft,hyperlinkURL,hyperlinkBracketsRight containedin=ALL
  if (s:conceal_aggressively == 1)
      syntax match hyperlinkBracketsLeft	contained "\[\{2}#\?"     conceal
  else
      syntax match hyperlinkBracketsLeft	contained "\[\{2}"     conceal
  endif
  syntax match hyperlinkURL				    contained "[^][]*\]\[" conceal
  syntax match hyperlinkBracketsRight	contained "\]\{2}"     conceal
  hi def link hyperlink Underlined
endif
```
Now I am able to disable the vim-orgmode link highlighting with the following line in my .vimrc:
```vim
let g:vim_orgmode_conceal_hyperlinks=0
```

**Comment by seflue** [comment]
For vim-polyglot you also have the option, to disable a certain filetype plugin, e.g.
```vim
let g:polyglot_disabled = ['org']
```

**Comment by yamsu** [comment]
@seflue thanks for solving this. The following works!

> For vim-polyglot you also have the option, to disable a certain filetype plugin, e.g.
> 
> ```viml
> let g:polyglot_disabled = ['org']
> ```

However, It would be great to put in a pull request for the orgmode_conceal_hyperlinks option.
