### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Iterable' in Python 3.10.1-1

### ISSUE THREAD

**Issue by martonbalazs** [jceb/vim-orgmode#374]
Just got an upgrade of Python to 3.10.1-1 in Arch and vim-orgmode cannot fold anymore, droping the error

AttributeError: module 'collections' has no attribute 'Iterable' .

**Comment by cxwx** [comment]
same problem

**Comment by elig0n** [comment]
https://github.com/jceb/vim-orgmode/pull/373

**Comment by martonbalazs** [comment]
Thanks a lot, much appreciated. It works fine now on Arch.

**Comment by jbpoittevin** [comment]
Fixed with pull request #373.
