### ISSUE TITLE
Python 3.12 and `imp`

### ISSUE THREAD

**Issue by jhrr** [jceb/vim-orgmode#390]
The package no longer functions if Vim is compiled with Python 3.12 because the previously only deprecated `imp` module, which is [used here](https://github.com/jceb/vim-orgmode/blob/b27feaba9a316e8307cfd7a56797b378fb52df83/ftplugin/orgmode/_vim.py#L10) is no longer available.

```
Python 3.11.6 (main, Oct 15 2023, 14:34:59) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import imp
<stdin>:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
```
```
Python 3.12.0 (main, Oct  5 2023, 15:44:07) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import imp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'imp'
```

**Comment by jbpoittevin** [comment]
@jhrr can you validate correction with branch deprecated_imp please ?

**Comment by jhrr** [comment]
@jbpoittevin yep, I can confirm that installing with `deprecated_imp` is working here 👍

**Comment by jbpoittevin** [comment]
@jhrr thanks for your action.
Merged in branch master.
