### ISSUE TITLE
Use python 2.7

### ISSUE THREAD

**Issue by sotte** [jceb/vim-orgmode#91]
It would be nice to use some of the features of python 2.7 (ordereddict, unittest2, and more). Also a port to python 3.x would be easier. (With python 3.x the encode/decode shouldn't be necessary anymore, right?)

Most 'modern' distributions already ship 2.7.

**Comment by Shurakai** [comment]
I'm planning to do some work on vim-orgmode and I'd like to see orgmode move to Python 3, too.

**Comment by Titan-C** [comment]
I would also like the python 3 move.

**Comment by jceb** [comment]
I'm also up for Python 3.  Is it possible to run Python 2 and Python 3 plugins together in one vim instance?  As far as I can remember this was a limitation I came across that supported my decision for Python 2 since most plugins only supported version 2 back then.

**Comment by Titan-C** [comment]
I didn't do a big test. But at least in arch linux you can install vim and neovim, both with Python 2 and Python 3 support at the same time. There is no conflict, but you have to specify which you are calling

**Comment by jceb** [comment]
Thank you for the hint.

**Comment by jbpoittevin** [comment]
Python 2.7 is obsolete now. Closing issue, code is working fine with python 3.10.
Please open individual issues for python 3 problems, if encountered any.
